### ISSUE TITLE
Bug: Unable to check file patterns from the default conventions, it instead checks that the file doesn't exist

### ISSUE THREAD

**Issue by dietergeerts** [tal-rofe/Inflint#132]
### Environment

Node version: v18.16.0
npm version: 9.5.1
Local Inflint version: 2.0.0
Global Inflint version: -
Operating System: Windows, running in a docker container that has Ubuntu

### What did you do?

I created a configuration that should throw errors for sure on the filename convention, as our files are current PascalCase for vue components, which is what we want. This configuration works in the sense that it does find all the vue files, but instead of throwing an error on incorrect filename pattern, it throws an error that this file shouldn't exist.

<details>
<summary>Configuration</summary>

```
{
  "rules": {
    "**/*.vue": [
      "error",
      "kebab-case"
    ]
  }
}
```
</details>

### What did you expect to happen?

An error reporting that the filename pattern isn't following the required one defined in the config.

### What actually happened?

An error reporting that the file is unexpected, thus it should not exist.

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

The docs are really strange, in that they tell that the filename convention set in the config is checked in a way that there should NOT be any files with that convention, which is very weird already, so I was hoping that this is an error in the docs themselves. Then, when the convention isn't one of the pre-defined ones, the docs state that it's then seen as a regex, and when I indeed use a regex, it seems when the regex matches the actual filename, no error is reported. I tried to debug the code, but it's so strange, because we indeed define patterns to tell which files we want to check the pattern on, but it then first check if these files exist and throw an error already, which is not what is expected. Am I really misunderstanding this all? I'm getting really confused :D

**Comment by tal-rofe** [comment]
@dietergeerts 
You are right. The docs are indeed misleading. When one wants to enforce some convention over some files/folders, let's say `PascalCase`, the rule should be `...['error', 'PascalCase']`. Currently the docs describes this rule as `inflint` emits error if **there are** files/folder with this convention, which is wrong against the package logic. This one fixed.

**Comment by tal-rofe** [comment]
@dietergeerts 
How would you change the configuration for a rule in that way, where an existence error will be configured in the options?
It'd be great if you provide examples for configurations for existence check and for convention check.

**Comment by dietergeerts** [comment]
Thanks for the fix!

I don't really use the existence checks, only the convention one, so I didn't put much thought in that one yet. It might be helpful though to disallow certain files in certain directories, but with all other linting tools, I guess this need didn't rose yet on the project I'm working on right now. I think what you could do for existence is `{ './src/**/*': ['error', { checkExistence: true }] }`, which then will allow an extra use-case, where you could disallow certain conventions and allow all others with `{ './src/**/*': ['error', 'convention', { checkExistence: true }] }`

**Comment by tal-rofe** [comment]
> Thanks for the fix!
> 
> I don't really use the existence checks, only the convention one, so I didn't put much thought in that one yet. It might be helpful though to disallow certain files in certain directories, but with all other linting tools, I guess this need didn't rose yet on the project I'm working on right now. I think what you could do for existence is `{ './src/**/*': ['error', { checkExistence: true }] }`, which then will allow an extra use-case, where you could disallow certain conventions and allow all others with `{ './src/**/*': ['error', 'convention', { checkExistence: true }] }`

As the existence check is a feature as same as convention check is, it does not make sense for me to "enable" the feature by an option field. And also, what would `{ './src/**/*': 'error' }` would mean?

But you did bring up an extra use-case to disallow conventions. The option field should be `disallow` (and not `checkExistence`) with default value of `false` (because right now the behavior is to only allow the "convention" to exist). **And, allow to configure multiple conventions by providing an array instead of 1 string**. This solves both ways: Either you disallow multiple conventions, or you allow multiple conventions.
